version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: rms1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "cd src &&  npx prisma db push && npm start"

volumes:
  postgres_data:

